"""init

Revision ID: dff3d9d382f8
Revises:
Create Date: 2024-09-28 17:30:32.208401

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dff3d9d382f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tg_users",
        sa.Column("telegram_id", sa.VARCHAR(length=255), nullable=False),
        sa.Column("username", sa.VARCHAR(length=255), nullable=True),
        sa.Column("mention", sa.VARCHAR(length=255), nullable=True),
        sa.Column("full_name", sa.VARCHAR(length=255), nullable=True),
        sa.Column("phone", sa.VARCHAR(length=255), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tg_users_telegram_id"), "tg_users", ["telegram_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tg_users_telegram_id"), table_name="tg_users")
    op.drop_table("tg_users")
    # ### end Alembic commands ###
